language: node_js
node_js:
- '0.10'
- '0.11'
before_install: git clone https://github.com/visionmedia/node-jscoverage.git; cd node-jscoverage; ./configure; make;  cd ..
script: npm run-script coveralls
